#!/bin/sh
#PBS -j oe
#PBS -o Logfile
#PBS -l procs=1
#PBS -N OF_CHT
#PBS -q dev
#PBS -l walltime=4:00:00
cd ${0%/*} || exit 1    # Run from this directory

# Load required modules ...
#source /etc/profile.d/modules.sh
#module add application/OpenFOAM/openfoam-5.x.intel18

# Source OF bashrc ...
#source /home/software/OpenFOAM/OpenFOAM-5.x.intel18/etc/bashrc

#cd /home/stw/data/OpenFoamRuns/ConjugatedHeatTransfer_01/planeWall_Testdatensatz/

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanTimeDirectories	# cleanCase
rm -rf VTK
rm -rf TDAC
rm -rf 0/topAir
rm -rf 0/wall
rm -f 0/cellToRegion

rm -rf constant/topAir/polyMesh
rm -rf constant/wall/polyMesh
rm -rf constant/cellToRegion 
rm -rf constant/polyMesh/sets

rm -f constant/topAir/F
rm -f constant/topAir/constructMap*
rm -f constant/topAir/finalAgglom
rm -f constant/topAir/globalFaceFaces
rm -f constant/topAir/subMap

rm -rf postProcessing
rm -rf processor*

rm -f Res_*

rm -rf constant/polyMesh

#------------------------------------------------------------------------------
